In [13]:
import numpy as np
import sympy as sp
import modern_robotics as mr
from Oppg2.Utilities.RobotClass import *
from Oppg2.Utilities.kukaKinematics import Mlist, Slist

In [61]:

KUKup = Robot( Mlist, ['z', '-z', 'x', 'x', 'z','z'])
KUKdown = Robot( Mlist, ['z', '-z', 'x', 'x', 'z','x'])

In [62]:
#Kan finne S_list fra M!
# KUK.draw_robot()
# KUK.allToOrigin()
# KUK.draw_robot()
KUKdown.links[0].set_colour([1,0,0])
KUKdown.links[1].set_colour([0,1,0])

# KUKdown.transform(S_list, [-1.1416,  1.038 , -4.2855, -1.5708,  1.5708, -0.2475])
# KUKup.draw_robot()
# KUKdown.draw_robot()
# array([-1.1416, -1.3258,  1.3102, -1.5708,  1.5708,  2.9844]),
#  array([-1.1416,  1.038 , -4.2855, -1.5708,  1.5708, -0.2475])

# KUKup.transform(S_list, [-1.1416, -1.3258,  1.3102, -1.5708,  1.5708,  2.9844])
KUKup.draw_robot()


WebVisualizer(window_uid='window_31')

WebVisualizer(window_uid='window_32')

In [ ]:
array([ -65.4084,   59.4744, -245.5405,  -90.    ,   90.    ,  -14.1788])
array([-65.4084, -75.9631,  75.0678, -90.    ,  90.    , 170.992 ])